### obtener todos los characters
GET http://localhost:3000/api/rols

### obtener un character
GET http://localhost:3000/api/rols/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo character
POST http://localhost:3000/api/rols
Content-Type: application/json

{
    "name": "Cliente",
    "description": "Cliente regular"
}

### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/rols/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "name": "Empleado",
    "description": "Empleado irregular"
}

### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/rols/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "name": "Cliente exclusivo",
}

### borrar un character 
DELETE http://localhost:3000/api/rols/a02b91bc-3769-4221-beb1-d7a3aeba7dad
