### obtener todos los characters
GET http://localhost:3000/api/rols

### obtener un character
GET http://localhost:3000/api/rols/a02b91bc-3769-4221-beb1-d7a3aeba7dad

### crear un nuevo character
POST http://localhost:3000/api/rols
Content-Type: application/json

{
    "name": "Client",
    "description": "Regular client"
}

### modificar un character (PUT - recurso completo e idempotente)
PUT http://localhost:3000/api/rols/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "name": "Employee",
    "description": "Irregular employee"
}

### modificar un character (PATCH - recurso parcial)
PATCH http://localhost:3000/api/rols/a02b91bc-3769-4221-beb1-d7a3aeba7dad
Content-Type: application/json

{
    "name": "Exclusive client",
}

### borrar un character 
DELETE http://localhost:3000/api/rols/a02b91bc-3769-4221-beb1-d7a3aeba7dad
